stages:
  - dependencies
  - build
  - test
  - migrate
  - deploy

cache:
  paths:
    - vendor/
    - node_modules/

variables:
  FTP_HOST: "77,245,159,131"
  FTP_USERNAME: "mohsen@dhr-solutions.com"
  FTP_PASSWORD: "mohsen@2024"
  FTP_ROOT: "" # Example: /var/www/html
  COMPOSER_ALLOW_SUPERUSER: 1
  NODE_ENV: "production"

before_script:
  - echo "Starting pipeline..."
  - echo "Setting up environment variables..."

dependencies:
  stage: dependencies
  image: composer:latest
  script:
    - echo "Installing required PHP extensions..."
    - docker-php-ext-install exif
    - echo "Installing PHP dependencies using Composer..."
    - composer install --prefer-dist --no-dev --no-interaction --optimize-autoloader
  artifacts:
    paths:
      - vendor/

build:
  stage: build
  image: node:16-alpine
  script:
    - echo "Installing Node.js dependencies..."
    - npm install
    - echo "Installing Laravel Mix globally..."
    - npm install --global laravel-mix
    - echo "Building assets for production..."
    - npm run prod
  artifacts:
    paths:
      - public/js/
      - public/css/
      - public/mix-manifest.json

test:
  stage: test
  image: php:8.2-cli
  script:
    - echo "Running Laravel tests..."
    - vendor/bin/phpunit --testdox

migrate:
  stage: migrate
  image: php:8.2-cli
  script:
    - echo "Caching Laravel configuration..."
    - php artisan config:cache
    - echo "Caching Laravel routes..."
    - php artisan route:cache
    - echo "Caching Laravel views..."
    - php artisan view:cache
    - echo "Running migrations..."
    - php artisan migrate --force

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Starting deployment via FTP..."
    - apk add --no-cache lftp
    - echo "Uploading files to FTP server..."
    - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -R --delete --verbose ./ $FTP_ROOT"
    - echo "Deployment completed."
