deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y lftp
  script:
    - echo "Starting deployment to FTP server $FTP_SERVER... with $FTP_USERNAME && $FTP_PASSWORD "
    - lftp -d -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_SERVER" -e "
      set ftp:ssl-allow no;
      mirror --reverse --delete --verbose ./ /public_html/dhr-solutions;
      bye;
      "
