deploy:
  stage: deploy
  image: php:8.2-cli  # Use PHP 8.2 for compatibility with symfony/css-selector and other dependencies
  before_script:
    # Update package lists and install necessary tools
    - apt-get update && apt-get install -y unzip lftp
    # Install Composer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    # Enable ext-exif PHP extension
    - docker-php-ext-install exif && docker-php-ext-enable exif
  script:
    - echo "Installing Composer dependencies..."
    # Install dependencies optimized for production
    - composer install --no-dev --optimize-autoloader
    - echo "Starting deployment to FTP server $FTP_SERVER..."
    # Deploy files using lftp
    - lftp -d -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_SERVER" -e "
      set ftp:ssl-force true;
      set ftp:ssl-protect-data true;
      set ftp:ssl-allow yes;
      set ssl:verify-certificate no;
      mirror --reverse --delete --verbose ./ /public_html/dhr-solutions;
      bye;
      "
    - echo "Deployment completed successfully!"
