deploy:
  stage: deploy
  image: php:8.2-cli
  before_script:
    - apt-get update && apt-get install -y unzip lftp
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - docker-php-ext-install exif && docker-php-ext-enable exif
  script:
    - echo "Installing Composer dependencies..."
    - composer install --no-dev --optimize-autoloader
    - echo "Starting deployment to FTP server $FTP_SERVER..."
    - |
      lftp -d -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_SERVER" -e "
      set ftp:ssl-force true;
      set ftp:ssl-protect-data true;
      set ftp:ssl-allow yes;
      set ssl:verify-certificate no;
      set mirror:parallel-transfer-count 4;
      set mirror:use-cache true;
      set mirror:skip-noaccess true;
      set mirror:use-permissions false;
      set mirror:check-file-size true;
      set cmd:trace true;
      set log:enabled true;
      set log:file lftp-deployment.log;
      mirror --reverse --only-newer --verbose ./ /public_html/dhr-solutions;
      bye;
      "
    - echo "Deployment completed successfully!"

