deploy:
  stage: deploy
  image: php:8.2-cli
  before_script:
    # Install necessary tools
    - apt-get update && apt-get install -y unzip lftp git
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - docker-php-ext-install exif && docker-php-ext-enable exif
  script:
    - echo "Installing Composer dependencies..."
    - composer install --no-dev --optimize-autoloader

    # Identify changed files
    - echo "Generating list of changed files..."
    - git diff --name-only HEAD~1 > changed-files.txt
    - echo "Changed files:"
    - cat changed-files.txt

    # Upload only changed files
    - echo "Uploading changed files..."
    - |
      while read file; do
        lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_SERVER" -e "
        set ftp:ssl-force true;
        set ftp:ssl-protect-data true;
        set ftp:ssl-allow yes;
        set ssl:verify-certificate no;
        put -O /public_html/dhr-solutions $file;
        bye;
        "
      done < changed-files.txt
    - echo "Deployment completed successfully!"
  timeout: 1h
