deploy:
  stage: deploy
  image: php:8.2-cli
  before_script:
    # Install necessary tools
    - apt-get update && apt-get install -y unzip lftp git
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - docker-php-ext-install exif && docker-php-ext-enable exif
  script:
    - echo "Installing Composer dependencies..."
    - composer install --no-dev --optimize-autoloader

    # Fetch all branches to ensure we have the correct reference
    - git fetch --all

    # Determine last deployed commit
    - echo "Determining last deployed commit..."
    - |
      if [ -f last-deployed-commit.txt ]; then
        LAST_DEPLOYED_COMMIT=$(cat last-deployed-commit.txt);
        echo "Last deployed commit: $LAST_DEPLOYED_COMMIT";
        git diff --name-only "$LAST_DEPLOYED_COMMIT" HEAD > changed-files.txt;
      else
        echo "No previous deployment found. Deploying all files...";
        git diff --name-only HEAD > changed-files.txt;
      fi

    # Output changed files
    - echo "Changed files:"
    - cat changed-files.txt

    # Upload only changed files
    - echo "Uploading changed files..."
    - |
      while read file; do
        lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_SERVER" -e "
        set ftp:ssl-force true;
        set ftp:ssl-protect-data true;
        set ftp:ssl-allow yes;
        set ssl:verify-certificate no;
        put -O /public_html/dhr-solutions $file;
        bye;
        "
      done < changed-files.txt

    # Save the current commit as the last deployed commit
    - echo "Saving the current commit as the last deployed commit..."
    - git rev-parse HEAD > last-deployed-commit.txt
    - echo "Deployment completed successfully!"
  timeout: 1h
