name: Build and Deploy Laravel Project

on:
  workflow_dispatch: # يسمح بتشغيل العملية يدويًا
  push:
    branches:
      - main

jobs:
  build:
    name: Build Laravel Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: exif

      - name: Install Composer Dependencies
        run: |
          composer install --prefer-dist --no-dev --no-interaction --optimize-autoloader

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node.js Dependencies
        run: |
          npm install
          npm install --global webpack webpack-cli
          npm install resolve-url-loader@^5.0.0 --save-dev --legacy-peer-deps

      - name: Build Assets
        run: npx mix --production

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            public/js/
            public/css/
            public/mix-manifest.json
            vendor/

  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Prepare Environment
        run: |
          echo "====================================="
          echo "Preparing environment for deployment..."
          sudo apt-get update
          echo "Installing lftp..."
          sudo apt-get install -y lftp
          echo "Environment setup completed successfully."
          echo "====================================="

      - name: Deploy Files to FTP Server
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
        run: |
          echo "====================================="
          echo "Starting FTP Deployment Process..."
          echo "Connecting to FTP server: ${FTP_SERVER}"
          echo "Using FTP username: ${FTP_USERNAME}"
          echo "====================================="
          lftp -d -c "
            echo '--- Setting FTP options...';
            set ssl:verify-certificate no;  # تعطيل التحقق من الشهادات (اختياري)
            set ftp:passive-mode yes;       # استخدام الوضع السلبي للاتصال
            set net:timeout 60;             # ضبط وقت المهلة
            echo '--- Connecting to server...';
            open -u ${FTP_USERNAME},${FTP_PASSWORD} ${FTP_SERVER};
            echo '--- Connected to FTP server.';
            echo '--- Listing remote directory...';
            ls;
            echo '--- Starting file upload...';
            mirror --reverse --delete --verbose ./;
            echo '--- Upload completed successfully.';
          "
          if [ $? -ne 0 ]; then
            echo "Error: Deployment failed."
            exit 1
          else
            echo "Deployment completed successfully."
          fi
